services:
  iupd:
    build:
      context: .
    container_name: iupd-container
    network_mode: bridge
    user: root
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - ${VOLUMN_MAPPING}
    command: python3 main.py
    environment:
      - DEBIAN_FRONTEND=noninteractive
      - APP_ENV=${APP_ENV}
      - UUID=${UUID}
      - REMOTE_STORAGES=${REMOTE_SERVERS}
      - REMOTE_STORAGES_USERS=${REMOTE_SERVER_USERS}
      - REMOTE_STORAGES_PASSWORDS=${REMOTE_SERVER_PASSWORDS}
      - CENTRALIZED_SERVER=${CENTRALIZED_SERVER}
      - TARGET_FILE=${TARGET_FILE}
      - INTERMEDIATE_OUTPUT_FILE=${INTERMEDIATE_OUTPUT_FILE}
      - RESULT_FOLDER=${RESULT_FOLDER}
      - PROBE_RATE=${PROBE_RATE}
      - MAX_TTL=${MAX_TTL}
